version: "3.9"
services:
  web-static:
    build: ../step1
    expose: 
      - "80"
    labels:
      - "traefik.http.services.web-static.loadbalancer.sticky.cookie.name=session"
      - "traefik.http.routers.web-static.rule=PathPrefix(`/`)"
  web-dynamic:
    build: ../step2
    expose:
      - "80"
    labels:
      #create http router web-dynamic with a rule of PathPrefix(`/dyn/`)
      - "traefik.http.routers.web-dynamic.rule=PathPrefix(`/dyn/`)"
      #create the middleware stripPrefix that strips /dyn/ from the request path
      - "traefik.http.middlewares.dynPrefix.stripprefix.prefixes=/dyn/"
      #register the middleware stripPrefix to the router web-dynamic
      - "traefik.http.routers.web-dynamic.middlewares=dynPrefix"

  control:
    build: ../control-ui
    expose:
      - "80"
    labels:
      - "traefik.http.routers.web-control.rule=PathPrefix(`/control/`)"
      - "traefik.http.middlewares.controlPrefix.stripprefix.prefixes=/control/"
      - "traefik.http.routers.web-control.middlewares=controlPrefix"
    environment:
      - PREFIX=control/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  reverse-proxy:
    image: traefik:v2.5
    command: --api.insecure=true --providers.docker --accesslog=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock